// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.0
// source: proto/monolit.proto

package monolit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Monolit_HealthCheck_FullMethodName = "/otus.monolit/HealthCheck"
)

// MonolitClient is the client API for Monolit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonolitClient interface {
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type monolitClient struct {
	cc grpc.ClientConnInterface
}

func NewMonolitClient(cc grpc.ClientConnInterface) MonolitClient {
	return &monolitClient{cc}
}

func (c *monolitClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Monolit_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonolitServer is the server API for Monolit service.
// All implementations must embed UnimplementedMonolitServer
// for forward compatibility
type MonolitServer interface {
	HealthCheck(context.Context, *emptypb.Empty) (*HealthResponse, error)
	mustEmbedUnimplementedMonolitServer()
}

// UnimplementedMonolitServer must be embedded to have forward compatible implementations.
type UnimplementedMonolitServer struct {
}

func (UnimplementedMonolitServer) HealthCheck(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMonolitServer) mustEmbedUnimplementedMonolitServer() {}

// UnsafeMonolitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonolitServer will
// result in compilation errors.
type UnsafeMonolitServer interface {
	mustEmbedUnimplementedMonolitServer()
}

func RegisterMonolitServer(s grpc.ServiceRegistrar, srv MonolitServer) {
	s.RegisterService(&Monolit_ServiceDesc, srv)
}

func _Monolit_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonolitServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Monolit_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonolitServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Monolit_ServiceDesc is the grpc.ServiceDesc for Monolit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Monolit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "otus.monolit",
	HandlerType: (*MonolitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _Monolit_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/monolit.proto",
}
