version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app_network

  grafana:
    image: grafana/grafana:10.4.15
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
      - zabbix-server
    ports:
      - '4000:3000'
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - app_network

  zabbix-db:
    image: docker.io/bitnami/postgresql:14.5.0
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: zabbix
      POSTGRESQL_POSTGRES_PASSWORD: root
    volumes:
      - ../data/pg_zabbix_data:/bitnami/postgresql
    networks:
      - app_network

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    depends_on:
      - zabbix-db
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zabbix
    networks:
      - app_network
    ports:
      - "10051:10051"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    depends_on:
      - zabbix-db
      - zabbix-server
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zabbix
      - ZBX_SERVER_HOST=zabbix-server
    networks:
      - app_network
    ports:
      - "8080:8080"

#  zabbix-agent:
#    image: zabbix/zabbix-agent
#    environment:
#      ZBX_SERVER_HOST: zabbix-server
#    depends_on:
#      - zabbix-server
#    networks:
#      - app_network

volumes:
  grafana:
    
networks:
  app_network:
    external: true