app:
  name: otus-arch
  secret: my-secret
db:
  read:
    - host: localhost
      port: 6433
      user: postgres
      password: postgres
      database: facebook
    - host: localhost
      port: 6434
      user: postgres
      password: postgres
      database: facebook
  write:
    - host: localhost
      port: 6432
      user: postgres
      password: postgres
      database: facebook
  shard:
    - host: localhost
      port: 7432
      user: postgres
      password: postgres
      database: facebook

http:
  host: localhost
  port: 8080
cache:
  host: localhost
  port: 6389
  password: redis
  user: default
kafka:
  host: localhost
  port: 29092